project_id = "bpsqyaxdhqejozmlejcb"

[functions.update-asaas-bank-account]
verify_jwt = true

[functions.create-asaas-wallet]
verify_jwt = true

[functions.create-asaas-payment]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.create-auth-user]
verify_jwt = true

[functions.notify]
verify_jwt = false

[functions.send-quote-to-suppliers]
verify_jwt = true

[functions.process-supplier-response]
verify_jwt = false

[functions.public-branding]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true
